{% if PY_VER == "3.8" %}
    {% set numpy_version = "1.19.5" %}
{% elif PY_VER in ["3.9", "3.10", "3.11"] %}
    {% set numpy_version = "1.23.3" %}
{% elif PY_VER in ["3.12", "3.13"] %}
    {% set numpy_version = "1.26.2" %}
{% endif %}

package:
  name: astropy
  version: "6.1.4"

build:
  number: 0

requirements:
  host:
    - numpy {{ numpy_version }}
