# This recipe contains a patch to add libpython to the link. It should be possible to
# apply this to any other package by copying the patch file and adjusting the paths.
#
# TODO: make this into a PR and submit it to upstream pybind11.

package:
  name: cmake_example
  version: "0.0.1"

build:
  number: 1

source:
  git_url: https://github.com/pybind/cmake_example.git
  git_rev: 8818f493e3698a3ab936cdd8e7144afae85df3f8

requirements:
  build:
    - cmake 3.28.1
  host:
    - python
